[tool.poetry]
name = "hushline"
version = "0.1.0"
description = ""
authors = ["Glenn Sorrentino <glenn@scidsg.org>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.9"
alembic = "1.13.1"
bcrypt = "4.1.2"
blinker = "1.7.0"
cffi = "1.16.0"
click = "8.1.7"
cryptography = "42.0.4"
dnspython = "2.4.2"
email-validator = "2.1.0.post1"
flask = "3.0.0"
flask-bcrypt = "1.0.1"
flask-migrate = "4.0.5"
flask-sqlalchemy = "3.1.1"
flask-wtf = "1.2.1"
greenlet = "3.0.3"
gunicorn = "21.2.0"
idna = "3.6"
itsdangerous = "2.1.2"
jinja2 = "3.1.3"
markupsafe = "2.1.3"
packaging = "23.2"
pycparser = "2.21"
pymysql = "1.1.0"
pyotp = "2.9.0"
python-dotenv = "1.0.0"
python-gnupg = "0.5.2"
qrcode = "7.4.2"
sqlalchemy = "2.0.25"
typing-extensions = "4.9.0"
werkzeug = "3.0.1"
wtforms = "3.1.2"
charset-normalizer = "3.3.2"
jsonify = "0.5"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
